name: Build and Test Price Classification API

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest

    - name: Deploy to GitHub Pages
      if: success() && github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        # Replace with your deployment steps
        echo "Deploying to GitHub Pages..."

        # Example: Deploying a Flask app to GitHub Pages
        # Generate HTML files (if needed)
        # python generate_html.py

        # Deploy to GitHub Pages
        # git config --global user.email "github-actions[bot]@users.noreply.github.com"
        # git config --global user.name "github-actions[bot]"
        # git checkout --orphan gh-pages
        # git add .
        # git commit -m "Deploy to GitHub Pages"
        # git push origin gh-pages --force

    - name: Notify on failure
      if: failure()
      run: |
        echo "Build and test failed! Check the workflow logs for details."

